[package]
name = "maia"
version = "0.0.2"
authors = ["Ognyan Makaveev"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = '0.19.0'
ansi_term = "0.12.1"
